import type { Metadata } from "next";
import { inter } from '@/app/fonts'
import "./globals.css";

export const metadata: Metadata = {
  title: "Perspective Funnel Preview",
  description: "Generated by nextjs' magic",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
